name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      meetups-backend: ${{ steps.filter.outputs.meetups-backend }}
      meetups-frontend: ${{ steps.filter.outputs.meetups-frontend }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          meetups-backend:
            - 'meetups-backend/**'
          meetups-frontend:
            - 'meetups-frontend/**'
            
  meetups-backend:
    needs: changes
    if: ${{ needs.changes.outputs.meetups-backend == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
      # meetups-backend folder working directory.
        working-directory: meetups-backend
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag meetups-backend:$(date +%s)
      
  meetups-frontend:
    needs: changes
    if: ${{ needs.changes.outputs.meetups-frontend == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
      # meetups-frontend folder working directory.
        working-directory: meetups-frontend
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag meetups-frontend:$(date +%s)
