name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:

  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      meetups-backend: ${{ steps.filter.outputs.meetups-backend }}
      meetups-frontend: ${{ steps.filter.outputs.meetups-frontend }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          meetups-backend:
            - 'meetups-backend/**'
          meetups-frontend:
            - 'meetups-frontend/**'
  
  # JOB to build and push backend image
  meetups-backend:
    needs: changes
    if: ${{ needs.changes.outputs.meetups-backend == 'true' }}
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         # meetups-backend folder working directory.
#         working-directory: meetups-backend
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:meetups-backend"
          push: true
          tags: yashgangwar123/meetups-backend:latest-from-github-action
 
  # JOB to build and push frontend image    
  meetups-frontend:
    needs: changes
    if: ${{ needs.changes.outputs.meetups-frontend == 'true' }}
    runs-on: ubuntu-latest
#     defaults:
#       run:
#         # meetups-frontend folder working directory.
#         working-directory: meetups-frontend
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:meetups-frontend"
          push: true
          tags: yashgangwar123/meetups-frontend:latest-from-github-action
